### DISCUSSION TITLE
Quarto Integration: error when rendering paths to website

### DISCUSSION THREAD

**Discussion by hershelm** [ropensci/targets#950] [Help]
I have a quarto.yml as follows

```
project:
  type: website
  render: 
    - "index.qmd"
    - "doc/index_1_data_readiness.qmd"
    - "doc/fill_rate_data_quality.qmd"

website:
  page-navigation: true
  title: "test"

  sidebar:
    contents:
      - href: index.qmd
        text: Executive Summary
      - section: doc/index_1_data_readiness.qmd
        contents:
        - doc/fill_rate_data_quality.qmd

format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto
```
