### ISSUE TITLE
Running tar_* with the pipeline in a subdirectory

### ISSUE THREAD

**Issue by wlandau** [ropensci/targets#957]
### Discussed in https://github.com/ropensci/targets/discussions/953

<div type='discussions-op-text'>

<sup>Originally posted by **TylerGrantSmith** October  7, 2022</sup>
I am trying to figure out what I am doing wrong configuration-wise.  At the top level of my R project I have a _targets.yaml file:

``` 
main:
  script: data-raw/_targets.R
  store: data-raw/_targets
  reporter_make: summary
```

I can only get `tar_make()` and `tar_outdated()` to run if I first change my working directory `setwd("./data-raw")`.  How can I configure the project so this step isn't required?  </div>
